apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: {{ .PolicyName }}
  namespace: default
spec:
  selector:
    matchLabels:
{{ .KeyValLabel }}
  file:
    matchDirectories:
    - dir: {{ .SecretMountPath }}
      recursive: true
  action:
    Block
