apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: k8s-secret-example-deployment-disable-secret-access
  namespace: default
spec:
  selector:
    matchLabels:
      app: k8s-secret-example

  file:
    matchDirectories:
    - dir: /etc/secret/
      recursive: true
  action:
    Block
